/**
 * postinstall-patch.js (auto-generated by build-doctor.sh)
 * Patches node_modules after npm install for Ionic 3 + Dart Sass.
 * Rules: NEVER modify src/ — only patch node_modules.
 */
const fs = require('fs');
const path = require('path');

// Patch 1: Fix ionic-angular multi-line SCSS strings
const scssFile = path.join('node_modules', 'ionic-angular', 'themes', 'ionic.functions.scss');
if (fs.existsSync(scssFile)) {
  let scss = fs.readFileSync(scssFile, 'utf8');
  if (scss.includes('$error-msg: "\n')) {
    scss = scss.replace(/\$error-msg:\s*"\n[\s\S]*?";/g, (m) => {
      const i = m.match(/\$error-msg:\s*"([\s\S]*?)";/);
      return i ? `$error-msg: "${i[1].replace(/\n\s*/g, ' ').trim()}";` : m;
    });
    fs.writeFileSync(scssFile, scss);
    console.log('✔ Patched ionic SCSS multi-line strings');
  } else { console.log('✔ ionic SCSS already patched'); }
}

// Patch 2: Silence Dart Sass deprecation warnings
const sassJs = path.join('node_modules', '@ionic', 'app-scripts', 'dist', 'sass.js');
if (fs.existsSync(sassJs)) {
  let s = fs.readFileSync(sassJs, 'utf8');
  if (!s.includes('logger:')) {
    s = s.replace(
      'node_sass_1.render(sassConfig,',
      'sassConfig.quietDeps=true;sassConfig.logger={warn:function(){}};node_sass_1.render(sassConfig,'
    );
    fs.writeFileSync(sassJs, s);
    console.log('✔ Patched sass.js — warnings silenced');
  } else { console.log('✔ sass.js already patched'); }
}
console.log('✔ postinstall patches complete');
